{{- $gen := ( include "webhook.gen-certs" . ) | fromJson }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "webhook.name" . }}-certs
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "webhook.name" . }}
    chart: {{ template "registry-mirror.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

data:
  tls.crt: {{ $gen.crt }}
  tls.key: {{ $gen.key }}

---
kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-webhook
webhooks:
  - name: registry-mirror.pipy.flomesh-io.cn
    namespaceSelector:
      matchExpressions:
      - key: pipy/webhook
        operator: NotIn
        values:
        - ignore
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    clientConfig:
      caBundle: {{ $gen.ca }}
      service:
        namespace: {{ .Values.namespace }}
        name: {{ .Release.Name }}
    admissionReviewVersions: ["v1", "v1beta1"]    
    sideEffects: None
    failurePolicy: Fail